const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36';
const js = await (await fetch('https://s1.hdslb.com/bfs/static/2233-monorepo/message-pc/static/js/index.f2b7bca0.js', { headers: { 'User-Agent': UA, Referer: 'https://message.bilibili.com/' } })).text();
const heads = [...new Set([...js.matchAll(/["'`]x-bili-[a-z0-9-]+["'`]/g)].map((m) => m[0]))];
console.log('x-bili headers:', heads.join(', '));
const mids = [...new Set([...js.matchAll(/with\("([A-Z_]+)"/g)].map((m) => m[1]))];
console.log('chain middleware:', mids.join(', '));
const i = js.indexOf('var dx=');
console.log('dx def:', i >= 0 ? js.slice(i, i + 400).replace(/\s+/g, ' ') : 'not found');
const j = js.indexOf('session_msgs');
console.log('session_msgs @', j, j >= 0 ? js.slice(j - 200, j + 200).replace(/\s+/g, ' ') : '');
