import { loadSession, cookieHeader } from './lib/cookies.js';
import { BiliClient } from './lib/api.js';
import { resolveConfig } from './lib/config.js';
import { signUrl } from './lib/wbi.js';
const session = loadSession();
const c = new BiliClient({ config: resolveConfig({}), session });
const keys = await c.wbiKeys();
const params = new URLSearchParams({ session_type: '1', group_fold: '1', unfollow_fold: '0', sort_rule: '2', build: '0', mobi_app: 'web', statistics: JSON.stringify({ appId: 100 }) });
const target = signUrl(`https://api.vc.bilibili.com/session_svr/v1/session_svr/get_sessions?${params}`, keys.imgKey, keys.subKey);
const res = await fetch(target, { headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36', Referer: 'https://message.bilibili.com/', Origin: 'https://message.bilibili.com', Cookie: cookieHeader(session.cookies ?? {}) } });
const text = await res.text();
console.log('http', res.status, text.slice(0, 600));
